name: tugas1
version: 1.0.0+1
publish_to: none
description: Tugas 1 Flutter (Profile).
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios : true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/icon.png"
  image_path: "assets/img/icon.png"
  web:
    generate: true
    image_path: "assets/img/icon.png"

flutter_native_splash:
  color: "#42a5f5"
  image: assets/img/icon.png
  android_12:
    image: assets/img/icon.png
    color: "#42a5f5"

  android: true
  ios: true
  web: true

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter: 
  uses-material-design: true
  assets:
    - assets/img/
  
  fonts:
    - family: cocogoose
      fonts:
        - asset: assets/font/Cocogoose Pro-trial.ttf



